title: Mr.Chang的博客
description: 一个基于Jekyll主题的个人博客

url: https://ibitbe.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about
 - title: 联系我
   url: /contact

social:
   github: ibitbe
   twitter: robbenemi
   facebook: robbenemi
   email: robbenemi@outlook.com

google_analytics: "UA-119923111-1"
google_ad_client: "ca-pub-3136189502549864"

